apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "certificate.labels" . | nindent 4 }}
    {{ toYaml .Values.labels | nindent 4 }}
spec:
  secretName: {{ .Values.secretName }}
  isCA: {{ .Values.isCA }}
  privateKey:
    algorithm: {{ default .Values.algorithm "RSA" }}
    encoding: PKCS1
    size: {{ default .Values.size 4096 }}
  dnsNames:
    {{ toYaml .Values.dnsNames | nindent 4 }}
  issuerRef:
    name: {{ .Values.issuer.name }}
    kind: {{ .Values.issuer.kind }}
    group: {{ default .Values.issuer.group "cert-manager.io" }}
